baseURL = 'https://niyunsheng.github.io/'
languageCode = 'en-us'
title = 'Yunsheng Ni'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[permalinks]
  tech = "/tech/:slug/"
  life = "/life/:slug/"

[params]
  env = "production"
  title = "Yunsheng Ni"
  description = "Engineering notes by Yunsheng Ni. Focusing on System Optimization, Custom Kernels, and Model Acceleration for LLMs & Video Generation."
  keywords = ["MLSys", "AI Infra", "LLM", "Video Generation", "Distributed Training", "Triton", "CUTLASS"]
  author = "Yunsheng Ni"
  
  defaultTheme = "auto" 
  
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true

  mainSections = ["tech", "life"]
  ShowHidden = true

  math = true

  comments = true
  
  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "Hi, I'm Yunsheng Ni ðŸ‘‹"
    Content = "Engineering notes on System Optimization & AI Algorithms.\nAlso sharing thoughts about life."

    [[params.profileMode.buttons]]
      name = "R&D Notes"
      url = "/tech"
    [[params.profileMode.buttons]]
      name = "Life"
      url = "/life"
    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/niyunsheng"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/niyunsheng"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:yunshengn@gmail.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "tech"
    name = "R&D Notes"
    url = "/tech/"
    weight = 10
  
  [[menu.main]]
    identifier = "life"
    name = "Life"
    url = "/life/"
    weight = 20

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 30

  [[menu.main]]
    identifier = "guestbook"
    name = "Guestbook"
    url = "/guestbook/"
    weight = 40

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]